import { Card } from "../ui/card";
import missingHeatmapImage from "../../../../image/eda_plots/missing_heatmap.png";
import revenueDistributionImage from "../../../../image/eda_plots/revenue_distribution.png";
import revenueTrendImage from "../../../../image/eda_plots/revenue_trend.png";
import adSpendDistributionImage from "../../../../image/eda_plots/ad_spend_distribution.png";
import adSpendTrendImage from "../../../../image/eda_plots/ad_spend_trend.png";
import profitDistributionImage from "../../../../image/eda_plots/profit_distribution.png";
import profitTrendImage from "../../../../image/eda_plots/profit_trend.png";
import unitsSoldDistributionImage from "../../../../image/eda_plots/units_sold_distribution.png";
import unitsSoldTrendImage from "../../../../image/eda_plots/units_sold_trend.png";
import refundRateTrendImage from "../../../../image/eda_plots/refund_rate_trend.png";
import activeUsersTrendImage from "../../../../image/eda_plots/active_users_trend.png";

type ExamplePlot = {
  title: string;
  src: string;
  alt: string;
};

type ReportFinding = {
  column: string;
  label: "Risk" | "Opportunity" | "Trend";
  score: string;
  hypothesis: string;
  keySignals: string;
  finding: string;
  plots?: ExamplePlot[];
};

const exampleFindings: ReportFinding[] = [
  {
    column: "revenue",
    label: "Risk",
    score: "0.365",
    hypothesis:
      "Revenue shows long-term growth but the latest period introduces a meaningful decline that needs explanation.",
    keySignals: "mean=19615.7008, std=14776.0380, variance=218331299.6537, skewness=1.4665",
    finding:
      "Revenue has historically trended upward, but August 2026 shows a 10.69% month-over-month drop and a 57.64% year-over-year decline. The long-run direction is still positive, yet the latest movement is large enough to justify immediate investigation into what changed in pricing, demand, or channel performance.",
    plots: [
      {
        title: "Revenue Distribution",
        src: revenueDistributionImage,
        alt: "Revenue distribution generated by the EDA agent",
      },
      {
        title: "Revenue Trend",
        src: revenueTrendImage,
        alt: "Revenue trend generated by the EDA agent",
      },
    ],
  },
  {
    column: "ad_spend",
    label: "Risk",
    score: "0.193",
    hypothesis:
      "Ad spending is inconsistent and materially lower than last year, which could limit near-term growth.",
    keySignals: "mean=2483.7952, std=2079.8401, variance=4325735.0215, skewness=1.5162",
    finding:
      "Ad spend is down more than 31% year-over-year, with a right-skewed distribution and irregular spikes. There is slight month-over-month improvement, but the broader pattern still looks like underinvestment or uneven campaign pacing that may be constraining revenue growth.",
    plots: [
      {
        title: "Ad Spend Distribution",
        src: adSpendDistributionImage,
        alt: "Ad spend distribution generated by the EDA agent",
      },
      {
        title: "Ad Spend Trend",
        src: adSpendTrendImage,
        alt: "Ad spend trend generated by the EDA agent",
      },
    ],
  },
  {
    column: "profit",
    label: "Risk",
    score: "0.169",
    hypothesis:
      "Profit has severe recent declines, and missing values plus outliers make the short-term picture less stable.",
    keySignals: "mean=831.2875, std=1562.8513, variance=2442504.3223, skewness=1.1614",
    finding:
      "Profit fell about 90% from the prior month and nearly 98% year-over-year. Forecasts still suggest a modest recovery, but roughly 9% missing records and visible outliers reduce confidence in the current performance story. This is the kind of column the agent should escalate early because both business impact and data-quality risk are present.",
    plots: [
      {
        title: "Profit Distribution",
        src: profitDistributionImage,
        alt: "Profit distribution generated by the EDA agent",
      },
      {
        title: "Profit Trend",
        src: profitTrendImage,
        alt: "Profit trend generated by the EDA agent",
      },
    ],
  },
  {
    column: "active_users",
    label: "Opportunity",
    score: "0.031",
    hypothesis:
      "Active user growth is accelerating and may create headroom for stronger conversion or monetization.",
    keySignals: "mean=3285.1522, std=944.7175, variance=892491.1081, skewness=0.3026",
    finding:
      "Active users are up 18.70% month-over-month and 33.97% year-over-year, with very few data-quality issues. The trend suggests strong underlying traction, making this a clear opportunity signal rather than a cleanup problem.",
    plots: [
      {
        title: "Active Users Trend",
        src: activeUsersTrendImage,
        alt: "Active users trend generated by the EDA agent",
      },
    ],
  },
  {
    column: "refund_rate",
    label: "Opportunity",
    score: "0.044",
    hypothesis:
      "The declining refund rate suggests improving customer satisfaction and more stable product performance.",
    keySignals: "mean=0.0426, std=0.0179, variance=0.0003, skewness=0.3537",
    finding:
      "Refund rate is down 8% from last month and about 41% year-over-year. The trend is favorable, the distribution is stable, and the missing-data burden is small, so this looks like a genuine improvement rather than a noisy artifact.",
    plots: [
      {
        title: "Refund Rate Trend",
        src: refundRateTrendImage,
        alt: "Refund rate trend generated by the EDA agent",
      },
    ],
  },
  {
    column: "channel",
    label: "Opportunity",
    score: "0.010",
    hypothesis:
      "A balanced channel mix reduces concentration risk and creates room to compare performance across acquisition paths.",
    keySignals: "unique_count=4, dominant_ratio=0.2574, entropy=1.9997, missing_ratio=0.0286",
    finding:
      "Channel usage is spread across four acquisition paths with no single source dominating the mix. The agent marks this as an opportunity because diversified coverage makes it easier to test, compare, and scale the best-performing channels without overdependence on one source.",
  },
  {
    column: "units_sold",
    label: "Trend",
    score: "0.147",
    hypothesis:
      "Units sold remain directionally positive, but the latest dip should be monitored to determine whether it is noise or the start of a slowdown.",
    keySignals: "mean=240.0687, std=134.1779, variance=18003.7106, skewness=1.1140",
    finding:
      "Units sold maintain a strong long-term upward trend, but August 2026 fell 22.31% from July and 54.24% compared with the same time last year. The report treats this as a trend watch item: not yet a confirmed deterioration, but important enough to track closely in the next cycles.",
    plots: [
      {
        title: "Units Sold Distribution",
        src: unitsSoldDistributionImage,
        alt: "Units sold distribution generated by the EDA agent",
      },
      {
        title: "Units Sold Trend",
        src: unitsSoldTrendImage,
        alt: "Units sold trend generated by the EDA agent",
      },
    ],
  },
];

function Section({
  eyebrow,
  title,
  summary,
  children,
}: {
  eyebrow: string;
  title: string;
  summary: string;
  children: React.ReactNode;
}) {
  return (
    <section className="space-y-6">
      <div className="space-y-3">
        <p className="text-sm font-semibold uppercase tracking-[0.2em] text-primary">
          {eyebrow}
        </p>
        <div className="space-y-2">
          <h4 className="text-2xl">{title}</h4>
          <p className="max-w-3xl text-base text-muted-foreground">{summary}</p>
        </div>
      </div>
      {children}
    </section>
  );
}

function PlotBlock({ plot }: { plot: ExamplePlot }) {
  return (
    <div className="space-y-3">
      <div className="overflow-hidden rounded-2xl border border-border/70 bg-background">
        <img src={plot.src} alt={plot.alt} className="h-auto w-full object-cover" />
      </div>
      <p className="text-sm font-medium text-foreground">{plot.title}</p>
    </div>
  );
}

function FindingCard({ finding }: { finding: ReportFinding }) {
  return (
    <Card className="space-y-5 border-border/70 bg-card/90 p-6 shadow-sm">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div className="space-y-1">
          <p className="text-lg font-semibold text-foreground">{finding.column}</p>
          <p className="text-sm text-primary">
            {finding.label} score: {finding.score}
          </p>
        </div>
        <span className="rounded-full border border-primary/20 bg-primary/10 px-3 py-1 text-xs font-semibold uppercase tracking-[0.16em] text-primary">
          {finding.label}
        </span>
      </div>

      <div className="space-y-4 text-sm leading-7 text-muted-foreground">
        <div>
          <p className="font-semibold text-foreground">Hypothesis</p>
          <p>{finding.hypothesis}</p>
        </div>
        <div>
          <p className="font-semibold text-foreground">Key signals</p>
          <p>{finding.keySignals}</p>
        </div>
        <div>
          <p className="font-semibold text-foreground">Finding</p>
          <p>{finding.finding}</p>
        </div>
      </div>

      {finding.plots && finding.plots.length > 0 && (
        <div className={`grid gap-5 ${finding.plots.length > 1 ? "xl:grid-cols-2" : ""}`}>
          {finding.plots.map((plot) => (
            <PlotBlock key={plot.title} plot={plot} />
          ))}
        </div>
      )}
    </Card>
  );
}

export function EDAAgentDashboard() {
  const riskFindings = exampleFindings.filter((item) => item.label === "Risk");
  const opportunityFindings = exampleFindings.filter((item) => item.label === "Opportunity");
  const trendFindings = exampleFindings.filter((item) => item.label === "Trend");

  return (
    <div className="space-y-10">
      <Card className="overflow-hidden border-primary/15 bg-gradient-to-br from-primary/8 via-card to-accent/10 p-8">
        <div className="space-y-5">
          <div className="inline-flex rounded-full border border-primary/20 bg-primary/10 px-3 py-1 text-xs font-semibold uppercase tracking-[0.18em] text-primary">
            Example EDA Report
          </div>
          <div className="space-y-3">
            <h3 className="text-3xl">Example report generated by the EDA agent</h3>
            <p className="max-w-4xl text-base leading-7 text-foreground/80">
              This section is intentionally shown as an example report generated by the EDA
              agent, not as a static hand-written case study. The goal is to show the format of
              the system output: a missing-value check first, then grouped findings across risk,
              opportunity, and trend, with the actual generated plots embedded as evidence.
            </p>
          </div>
          <div className="grid gap-3 md:grid-cols-4">
            <Card className="border-primary/15 bg-card/80 p-4">
              <p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">
                Coverage
              </p>
              <p className="mt-2 text-3xl text-primary">11/11</p>
              <p className="mt-2 text-sm text-muted-foreground">Columns analyzed in the run.</p>
            </Card>
            <Card className="border-primary/15 bg-card/80 p-4">
              <p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">
                Status
              </p>
              <p className="mt-2 text-3xl text-primary">PARTIAL</p>
              <p className="mt-2 text-sm text-muted-foreground">Stopped by MAX_COLUMNS_REACHED.</p>
            </Card>
            <Card className="border-primary/15 bg-card/80 p-4">
              <p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">
                Findings
              </p>
              <p className="mt-2 text-3xl text-primary">7</p>
              <p className="mt-2 text-sm text-muted-foreground">Selected example findings shown here.</p>
            </Card>
            <Card className="border-primary/15 bg-card/80 p-4">
              <p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">
                Report Date
              </p>
              <p className="mt-2 text-3xl text-primary">04.02</p>
              <p className="mt-2 text-sm text-muted-foreground">Generated from the latest sample run.</p>
            </Card>
          </div>
        </div>
      </Card>

      <Section
        eyebrow="Missing Values"
        title="The report opens with missingness before interpretation"
        summary="The first visual should establish whether the dataset is reliable enough to interpret. This example report starts with the generated missing-value heatmap so the user sees data quality before reading any claims."
      >
        <Card className="space-y-5 border-border/70 bg-card/90 p-6 shadow-sm">
          <div className="overflow-hidden rounded-2xl border border-border/70 bg-background">
            <img
              src={missingHeatmapImage}
              alt="Missing-value heatmap generated by the EDA agent"
              className="h-auto w-full object-cover"
            />
          </div>
          <p className="max-w-3xl text-sm leading-7 text-muted-foreground">
            The missingness check is intentionally placed at the beginning of the example report.
            In this run, profit has the most visible data-quality concern, while the rest of the
            tracked business metrics remain comparatively clean.
          </p>
        </Card>
      </Section>

      <Section
        eyebrow="Risk"
        title="High-priority findings are grouped into a risk section"
        summary="These are the columns the agent would escalate first because they combine business impact with recent deterioration, instability, or data-quality uncertainty."
      >
        <div className="space-y-6">
          {riskFindings.map((finding) => (
            <FindingCard key={finding.column} finding={finding} />
          ))}
        </div>
      </Section>

      <Section
        eyebrow="Opportunity"
        title="Positive signals are separated into opportunity findings"
        summary="The report does not only surface problems. It also highlights where growth, customer health, or diversification appears strong enough to support action."
      >
        <div className="space-y-6">
          {opportunityFindings.map((finding) => (
            <FindingCard key={finding.column} finding={finding} />
          ))}
        </div>
      </Section>

      <Section
        eyebrow="Trend"
        title="Trend findings stay distinct from immediate risk"
        summary="Some columns deserve monitoring rather than escalation. This section shows how the agent separates directional tracking from outright risk."
      >
        <div className="space-y-6">
          {trendFindings.map((finding) => (
            <FindingCard key={finding.column} finding={finding} />
          ))}
        </div>
      </Section>
    </div>
  );
}
