import { EDAAgentDashboard } from "./demos/EDAAgentDashboard";
import { ECGAnalysisDashboard } from "./demos/ECGAnalysisDashboard";

interface ProjectDemoProps {
  projectId: string;
}

export function ProjectDemo({ projectId }: ProjectDemoProps) {
  if (
    projectId === "teacher-allocation" ||
    projectId === "environmental-dashboard"
  ) {
    return null;
  }

  if (projectId === "eda-agent") {
    return (
      <div className="space-y-6">
        <p className="max-w-3xl text-sm text-muted-foreground">
          Example report generated by the EDA agent, with grouped findings and the real plot
          artifacts embedded directly into the writeup.
        </p>
        <EDAAgentDashboard />
      </div>
    );
  }

  if (projectId === "ecg-classification") {
    return (
      <div className="space-y-6">
        <p className="max-w-3xl text-sm text-muted-foreground">
          Structured notebook findings translated into reusable React charts for the ECG
          classification case study.
        </p>
        <ECGAnalysisDashboard />
      </div>
    );
  }
  return null;
}
